### ISSUE TITLE
No module named 'modules'

### ISSUE THREAD

**Issue by lzytniak** [Unknown22/TangoJSDemo#7]
![screen shot 2017-05-09 at 15 11 39](https://cloud.githubusercontent.com/assets/8569463/25852594/294a8d30-34ca-11e7-9dd9-acea3adba46b.png)

**Comment by Unknown22** [comment]
Could you show result of using `ls` in `modules` folder and `cat` on `__init__.py` in `modules` and main folder?

**Comment by lzytniak** [comment]
```
[lukzyt@b-v-bloch-cc-0]~/workspace/TangoJSDemo/src% python3.4 run_tangojs_demo.py 
You don't have npm. Do you want to install it now? (y/N): y
Password: Traceback (most recent call last):
  File "run_tangojs_demo.py", line 127, in _check_npm
    if 0 < int(_check_npm_version()) < 3:
  File "run_tangojs_demo.py", line 186, in _check_npm_version
    npm_version_check = subprocess.Popen(['npm', '-v'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'npm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_tangojs_demo.py", line 198, in <module>
    if check_system_compatibility() and _check_requirements():
  File "run_tangojs_demo.py", line 69, in _check_requirements
    requirements.append(_check_npm())
  File "run_tangojs_demo.py", line 145, in _check_npm
    out, err = npm_install.communicate()
  File "/usr/lib64/python3.4/subprocess.py", line 952, in communicate
    self.wait()
  File "/usr/lib64/python3.4/subprocess.py", line 1566, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib64/python3.4/subprocess.py", line 1514, in _try_wait
    (pid, sts) = _eintr_retry_call(os.waitpid, self.pid, wait_flags)
  File "/usr/lib64/python3.4/subprocess.py", line 491, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
[lukzyt@b-v-bloch-cc-0]~/workspace/TangoJSDemo/src% sudo python3.4 run_tangojs_demo.py
[sudo] password for lukzyt: 
Traceback (most recent call last):
  File "run_tangojs_demo.py", line 6, in <module>
    from modules.firefox import check_and_update_firefox
ImportError: No module named 'modules'
```

sudo python3.4 run_tangojs_demo.py - complain about module "modules" and without sudo it didn't.

**Comment by lzytniak** [comment]
Script have not permission to change firefox settings. Run this script again with administrator privilages or follow 'firefox.txt' in readme folder in this project

<img width="1239" alt="screen shot 2017-05-11 at 09 14 49" src="https://cloud.githubusercontent.com/assets/8569463/25937056/8d2f230e-362a-11e7-84a7-8907e3c61887.png">

**Comment by Unknown22** [comment]
Can you try run it with `sudo -E -H`?
Or try to add `Defaults env_keep += "PYTHONPATH"` to `/etc/sudoers`

**Comment by lzytniak** [comment]
```
[lukzyt@w-v-kitslab-cc-0]~/workspace/TangoJSDemo/src% python3.4 run_tangojs_demo.py 
Script have not permission to change firefox settings. Run this script again with administrator privilages or follow 'firefox.txt' in readme folder in this project
Couldn't configure firefox. Do you want to continue anyway? (y/N): N
You do not meet requirements.
[lukzyt@w-v-kitslab-cc-0]~/workspace/TangoJSDemo/src% sudo -E -H python3.4 run_tangojs_demo.py
[sudo] password for lukzyt: 
Traceback (most recent call last):
  File "run_tangojs_demo.py", line 9, in <module>
    from modules.firefox import check_and_update_firefox
ImportError: No module named 'modules'
[lukzyt@w-v-kitslab-cc-0]~/workspace/TangoJSDemo/src% sudo python3.4 run_tangojs_demo.py
Traceback (most recent call last):
  File "run_tangojs_demo.py", line 9, in <module>
    from modules.firefox import check_and_update_firefox
ImportError: No module named 'modules'
[lukzyt@w-v-kitslab-cc-0]~/workspace/TangoJSDemo/src%
```

It didn't help

**Comment by lzytniak** [comment]
Why Firefox require sudo privilege to change settings? Should be this available for all users?

**Comment by Unknown22** [comment]
![cf0aed94b9b95412ee50eb21a1538d6a](https://cloud.githubusercontent.com/assets/10746021/26166958/ac8edafe-3b35-11e7-8bd3-864dcd4cc96d.png)

This require sudo privilege to set global settings of firefox which are in folder you can't edit without it. Even firefox is saying that you shouldn't edit it if you don't know what you are doing.

**Comment by lzytniak** [comment]
Did you tried something this:
https://superuser.com/questions/823530/change-some-default-settings-for-firefox-globally
it seems that it does't require sudo privilege

**Comment by Unknown22** [comment]
New version doesn't require sudo privilages to change firefox configuration anymore. Try run it now.

**Comment by Unknown22** [comment]
Sudo privileges are not required anymore to change firefox settings. Try it now :)

**Comment by lzytniak** [comment]
```
1495136010743	addons.update-checker	WARN	Update manifest for aushelper@mozilla.org did not contain an updates property
1495136010755	addons.update-checker	WARN	Update manifest for e10srollout@mozilla.org did not contain an updates property
1495136010879	addons.update-checker	WARN	Update manifest for firefox@getpocket.com did not contain an updates property
1495136010890	addons.update-checker	WARN	Update manifest for webcompat@mozilla.org did not contain an updates property
1495136010901	addons.update-checker	WARN	Update manifest for {972ce4c6-7e08-4474-a285-3208198ce6fd} did not contain an updates property
```

![screen shot 2017-05-18 at 21 34 51](https://cloud.githubusercontent.com/assets/8569463/26220474/09206b38-3c13-11e7-9185-ea6852b11922.png)

**Comment by Unknown22** [comment]
What output do you have with `ls /home/{user}/.mozilla/firefox/` ?

**Comment by lzytniak** [comment]
```
[lukzyt@w-v-kitslab-cc-0]~% ls ~/.mozilla/firefox/
n1m9w0n6.default  profiles.ini
[lukzyt@w-v-kitslab-cc-0]~% where firefox         
/usr/bin/firefox
[lukzyt@w-v-kitslab-cc-0]~% 
```

**Comment by Unknown22** [comment]
Could you `cat` content of `~/.mozilla/firefox/n1m9w0n6.default/user.js`?

Did you try refresh site after browser run this blank site?

Mentioned warnings shoudn't be connected with this project. They are probably warnings for firefox addons you have installed.

**Comment by lzytniak** [comment]
```
[lukzyt@w-v-kitslab-cc-0]~% cat ~/.mozilla/firefox/n1m9w0n6.default/user.js
cat: /mxn/home/lukzyt/.mozilla/firefox/n1m9w0n6.default/user.js: No such file or directory
[lukzyt@w-v-kitslab-cc-0]~% ls -alt ~/.mozilla/firefox/n1m9w0n6.default/
total 4080
drwx------ 11 lukzyt MAX-Lab     4096 May 18 21:42 .
drwx------  3 lukzyt MAX-Lab     1024 May 18 21:42 datareporting
-rw-------  1 lukzyt MAX-Lab     8995 May 18 21:42 prefs.js
-rw-r--r--  1 lukzyt MAX-Lab    98304 May 18 21:42 webappsstore.sqlite
-rw-r--r--  1 lukzyt MAX-Lab 10485760 May 18 21:42 places.sqlite
-rw-------  1 lukzyt MAX-Lab      288 May 18 21:42 sessionCheckpoints.json
-rw-r--r--  1 lukzyt MAX-Lab      823 May 18 21:42 SiteSecurityServiceState.txt
-rw-------  1 lukzyt MAX-Lab      381 May 18 21:42 xulstore.json
-rw-r--r--  1 lukzyt MAX-Lab        0 May 18 21:42 SecurityPreloadState.txt
-rw-------  1 lukzyt MAX-Lab   131072 May 18 21:42 key3.db
-rw-------  1 lukzyt MAX-Lab    65536 May 18 21:42 cert8.db
-rw-r--r--  1 lukzyt MAX-Lab        0 May 18 21:42 AlternateServices.txt
drwx------  2 lukzyt MAX-Lab     1024 May 18 21:42 sessionstore-backups
-rw-------  1 lukzyt MAX-Lab     1112 May 18 21:42 sessionstore.js
drwx------  2 lukzyt MAX-Lab     1024 May 18 21:40 bookmarkbackups
-rw-------  1 lukzyt MAX-Lab     5650 May 18 21:38 extensions.json
-rw-------  1 lukzyt MAX-Lab    27953 May 18 21:36 blocklist-gfx.json
-rw-r--r--  1 lukzyt MAX-Lab  1048576 May 18 21:36 kinto.sqlite
-rw-------  1 lukzyt MAX-Lab   460296 May 18 21:36 blocklist-addons.json
-rw-------  1 lukzyt MAX-Lab   257951 May 18 21:36 blocklist.xml
-rw-------  1 lukzyt MAX-Lab   201408 May 18 21:36 blocklist-plugins.json
-rw-r--r--  1 lukzyt MAX-Lab    21414 May 18 21:36 revocations.txt
-rw-------  1 lukzyt MAX-Lab     2916 May 18 21:35 pluginreg.dat
-rw-r--r--  1 lukzyt MAX-Lab        0 May 18 21:35 .parentlock
-rw-r--r--  1 lukzyt MAX-Lab   524288 May 18 21:35 cookies.sqlite
-rw-------  1 lukzyt MAX-Lab       24 May 18 21:33 addons.json
drwx------  3 lukzyt MAX-Lab       80 May 11 20:13 gmp
-rw-------  1 lukzyt MAX-Lab      166 May 11 20:13 compatibility.ini
drwx------  2 lukzyt MAX-Lab     1024 May 11 09:12 saved-telemetry-pings
-rw-r--r--  1 lukzyt MAX-Lab   131072 May 11 09:12 permissions.sqlite
-rw-------  1 lukzyt MAX-Lab    24938 May 11 09:12 search.json.mozlz4
-rw-r--r--  1 lukzyt MAX-Lab      512 May 11 09:12 storage.sqlite
-rw-------  1 lukzyt MAX-Lab      809 May 11 09:11 containers.json
-rw-r--r--  1 lukzyt MAX-Lab      165 May 11 09:11 extensions.ini
-rw-------  1 lukzyt MAX-Lab       80 Mar 24 17:21 logins.json
drwxr-xr-x  2 lukzyt MAX-Lab     1024 Mar 24 17:21 webapps
-rw-r--r--  1 lukzyt MAX-Lab   196608 Jan 31 16:36 formhistory.sqlite
drwxr-xr-x  3 lukzyt MAX-Lab       80 Jan 31 13:53 gmp-gmpopenh264
drwx------  2 lukzyt MAX-Lab       80 Jan 31 13:53 healthreport
-rw-r--r--  1 lukzyt MAX-Lab     5011 Jan 31 13:53 mimeTypes.rdf
drwxr-xr-x  3 lukzyt MAX-Lab       80 Nov 21 21:08 storage
-rw-------  1 lukzyt MAX-Lab   165900 Aug 15  2016 search.json
-rw-r--r--  1 lukzyt MAX-Lab   229376 Aug 15  2016 content-prefs.sqlite
-rw-------  1 lukzyt MAX-Lab   131072 Aug 15  2016 secmod.db
drwx------  3 lukzyt MAX-Lab     1024 Aug 15  2016 ..
-rwx------  1 lukzyt MAX-Lab       29 Aug 15  2016 times.json
[lukzyt@w-v-kitslab-cc-0]~% 
```

**Comment by Unknown22** [comment]
What does script print right after you run it? Did you see something like that?

![firefoxconf](https://cloud.githubusercontent.com/assets/10746021/26222698/4db1f14c-3c1b-11e7-9e75-707efdd57c9e.PNG)

**Comment by lzytniak** [comment]
```
[lukzyt@w-v-kitslab-cc-0]~/workspace/TangoJSDemo% python3.4 -m tangojsdemo
Couldn't find default user profile for firefox. If you just installed firefox, open and close firefox, then run this script again.
Couldn't configure firefox. Do you want to continue anyway? (y/N): y
Compatibility and requirements: OK
tangojs-webapp-template@0.1.0 /mxn/home/lukzyt/workspace/TangoJSDemo/tangojs-webapp-template
└── tangojs-core@0.4.0 

tangojs-webapp-template@0.1.0 /mxn/home/lukzyt/workspace/TangoJSDemo/tangojs-webapp-template
└── tangojs-connector-local@0.4.1 

tangojs-webapp-template@0.1.0 /mxn/home/lukzyt/workspace/TangoJSDemo/tangojs-webapp-template
└── tangojs-web-components@0.4.6 


> tangojs-webapp-template@0.1.0 server /mxn/home/lukzyt/workspace/TangoJSDemo/tangojs-webapp-template

> http-server -c-1


Starting up http-server, serving ./

Available on:

  http://127.0.0.1:8080

  http://192.168.96.39:8080

Hit CTRL-C to stop the server

Error: GDK_BACKEND does not match available displays

```

**Comment by Unknown22** [comment]
Try pull new version. It should be fixed now.

**Comment by Unknown22** [comment]
If you will get npm error remove `tangojs-webapp-template` folder and run `npm cache clean`.

**Comment by lzytniak** [comment]
```
[lukzyt@w-v-kitslab-cc-0]~/workspace/TangoJSDemo% rm -rf tangojs-webapp-template
[lukzyt@w-v-kitslab-cc-0]~/workspace/TangoJSDemo% npm cache clean               
[lukzyt@w-v-kitslab-cc-0]~/workspace/TangoJSDemo% python3.4 -m tangojsdemo 
pref("dom.webcomponents.enabled",true);
pref("layout.css.grid.enabled",true);
Compatibility and requirements: OK
Cloning into 'tangojs-webapp-template'...
remote: Counting objects: 22, done.
remote: Total 22 (delta 0), reused 0 (delta 0), pack-reused 22
Receiving objects: 100% (22/22), 5.83 KiB | 0 bytes/s, done.
Resolving deltas: 100% (9/9), done.
tangojs-webapp-template@0.1.0 /mxn/home/lukzyt/workspace/TangoJSDemo/tangojs-webapp-template
├── html-imports-firefox-patch@0.1.0  (git://github.com/mliszcz/html-imports-firefox-patch.git#947520ba6129e815f7e2dce82a4491cde4092802)
├─┬ http-server@0.9.0 
│ ├── colors@1.0.3 
│ ├── corser@2.0.1 
│ ├─┬ ecstatic@1.4.1 
│ │ ├── he@0.5.0 
│ │ ├── mime@1.3.6 
│ │ ├── minimist@1.2.0 
│ │ └── url-join@1.1.0 
│ ├─┬ http-proxy@1.16.2 
│ │ ├── eventemitter3@1.2.0 
│ │ └── requires-port@1.0.0 
│ ├── opener@1.4.3 
│ ├─┬ optimist@0.6.1 
│ │ ├── minimist@0.0.10 
│ │ └── wordwrap@0.0.3 
│ ├─┬ portfinder@0.4.0 
│ │ ├── async@0.9.0 
│ │ └─┬ mkdirp@0.5.1 
│ │   └── minimist@0.0.8 
│ └─┬ union@0.4.6 
│   └── qs@2.3.3 
├── tangojs-connector-local@0.4.1 
├─┬ tangojs-connector-mtango@0.5.0 
│ ├── btoa@1.1.2 
│ └─┬ node-fetch@1.6.3 
│   ├─┬ encoding@0.1.12 
│   │ └── iconv-lite@0.4.17 
│   └── is-stream@1.1.0 
├── tangojs-core@0.4.0 
├─┬ tangojs-web-components@0.4.6 
│ ├─┬ chart.js@2.5.0 
│ │ └─┬ chartjs-color@2.1.0 
│ │   ├─┬ chartjs-color-string@0.4.0 
│ │   │ └── color-name@1.1.2 
│ │   └── color-convert@0.5.3 
│ └── moment@2.18.1 
└── webcomponents.js@0.7.24 

tangojs-webapp-template@0.1.0 /mxn/home/lukzyt/workspace/TangoJSDemo/tangojs-webapp-template
└── tangojs-core@0.4.0 

tangojs-webapp-template@0.1.0 /mxn/home/lukzyt/workspace/TangoJSDemo/tangojs-webapp-template
└── tangojs-connector-local@0.4.1 

tangojs-webapp-template@0.1.0 /mxn/home/lukzyt/workspace/TangoJSDemo/tangojs-webapp-template
└── tangojs-web-components@0.4.6 


> tangojs-webapp-template@0.1.0 server /mxn/home/lukzyt/workspace/TangoJSDemo/tangojs-webapp-template

> http-server -c-1


Starting up http-server, serving ./

Available on:

  http://127.0.0.1:8080

  http://192.168.96.39:8080

Hit CTRL-C to stop the server

Error: GDK_BACKEND does not match available displays
```

**Comment by Unknown22** [comment]
Do you run it on other machine through ssh? Cause this is error not connected with script itself.

[Check here](https://www.lightnetics.com/topic/1781/error-gdk_backend-does-not-match-available-displaysl)

**Comment by lzytniak** [comment]
You are right, it works!

<img width="729" alt="screen shot 2017-05-19 at 10 51 46" src="https://cloud.githubusercontent.com/assets/8569463/26241199/1ec963c4-3c84-11e7-8f14-245e8c029455.png">
